# golangci-lint configuration
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-blank: true
  gosec:
    severity: medium
    confidence: medium
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/postfixrelay/postfixrelay

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
